@host=http://localhost:3500


### CRITERIA
POST {{host}}/api/search/criteria HTTP/1.1
Content-Type: application/json
Content-Length: 141

	{
		"populationmin": "4800",
		"populationmax": "15000",
		"codedepartement": "77",
		"type_ecole": "Lycée",
		"distance_ecole_max": "1"
	}

### RANDOM
GET {{host}}/api/search/random HTTP/1.1

###

GET {{host}}/api/search/city?ville=354

###
GET {{host}}/api/search/random

###
POST {{host}}/api/search/city/54318/check?boolean=false
